src/main/java/it/iit/genomics/cru/smith/entity/SampleRun.java
package it.iit.genomics.cru.smith.entity;

import it.iit.genomics.cru.smith.hibernate.HibernateUtil;
import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

@Entity
@Table(name = "samplerun")
public class SampleRun implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    private SampleRunId id;

    @ManyToOne
    @JoinColumn(name = "sam_id", insertable = false, updatable = false)
    private Sample sample;

    @ManyToOne
    @JoinColumn(name = "operator_user_id")
    private User user;

    @ManyToOne
    @JoinColumn(name = "sequencing_reagent_code")
    private Reagent reagentBySequencingReagentCode;

    @ManyToOne
    @JoinColumn(name = "clustergeneration_reagent_code")
    private Reagent reagentByClustergenerationReagentCode;

    @ManyToOne
    @JoinColumn(name = "sampleprep_reagent_code")
    private Reagent reagentBySamplePrepReagentCode;

    @Column(name = "flowcell")
    private String flowcell;

	//@Column(name = "lane")
    //private int lane;
    @Column(name = "runfolder")
    private String runFolder;

    @Column(name = "iscontrol")
    private boolean isControl;

    @OneToMany
    @JoinColumns({
        @JoinColumn(name = "run_id", referencedColumnName = "run_id"),
        @JoinColumn(name = "sam_id", referencedColumnName = "sam_id")})
    private Set<RawData> rawDatas = new HashSet<RawData>(0);

    /*@OneToMany(mappedBy="lane_run_id")
     @JoinColumns( {
     @JoinColumn(name = "lane_run_id", referencedColumnName = "run_id"),
     @JoinColumn(name = "lane_sam_id", referencedColumnName = "sam_id") })
     private Set<Lane> lanes = new HashSet<Lane>(0);*/
    @OneToMany(mappedBy = "samplerun", fetch = FetchType.LAZY)
    private Set<Lane> lanes = new HashSet<Lane>(0);

    public SampleRun() {
    }

    public SampleRun(int id) {
        this.id = new SampleRunId(id, 0);

        this.sample = sample;
        this.user = user;
        this.reagentBySequencingReagentCode = new Reagent();
        this.reagentByClustergenerationReagentCode = new Reagent();
        this.reagentBySamplePrepReagentCode = new Reagent();
        this.flowcell = "";
        //this.lane = 0;
        this.runFolder = "";
        this.isControl = false;
        this.rawDatas = null;
    }

    public SampleRun(SampleRunId id, Sample sample, User user,
            Reagent reagentBySequencingReagentCode,
            Reagent reagentByClustergenerationReagentCode,
            Reagent reagentBySampleprepReagentCode, String flowcell,
            String runfolder, boolean iscontrol) {
        this.id = id;
        this.sample = sample;
        this.user = user;
        this.reagentBySequencingReagentCode = reagentBySequencingReagentCode;
        this.reagentByClustergenerationReagentCode = reagentByClustergenerationReagentCode;
        this.reagentBySamplePrepReagentCode = reagentBySampleprepReagentCode;
        this.flowcell = flowcell;
        //this.lane = lane;
        this.runFolder = runfolder;
        this.isControl = iscontrol;
    }

    public SampleRun(SampleRunId id, Sample sample, User user,
            Reagent reagentBySequencingReagentCode,
            Reagent reagentByClustergenerationReagentCode,
            Reagent reagentBySampleprepReagentCode, String flowcell,
            String runfolder, boolean iscontrol, Set<RawData> rawdatas) {
        this.id = id;
        this.sample = sample;
        this.user = user;
        this.reagentBySequencingReagentCode = reagentBySequencingReagentCode;
        this.reagentByClustergenerationReagentCode = reagentByClustergenerationReagentCode;
        this.reagentBySamplePrepReagentCode = reagentBySampleprepReagentCode;
        this.flowcell = flowcell;
        //this.lane = lane;
        this.runFolder = runfolder;
        this.isControl = iscontrol;
        this.rawDatas = rawdatas;
    }

    public SampleRun(int rid, int sid) {
        this.id = new SampleRunId(rid, sid);

    }

    public String getAllLanesToString1() {
        String toRet = "";
        for (Lane l : lanes) {
            toRet = toRet + " " + l.getLaneName();
        }
        return toRet;
    }
    
    public String getAllLanesToString(){
        Session session = HibernateUtil.getSessionFactory().openSession();        
        StringBuilder result = new StringBuilder();
        Transaction tx = null;
        try {
            tx = session.beginTransaction();
            SampleRun sr = (SampleRun)session.load(SampleRun.class, this.id);
            Set<Lane> ls = sr.getLanes();
            String toRet = "";
            for (Lane l : ls) {
                toRet = toRet + " " + l.getLaneName();
                result.append(l.getLaneName() + " ");
            }
            
            tx.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            if(session.isOpen()){
                session.flush();
                session.close();
            }
        }
        return result.toString().trim();
      
    }

    public SampleRunId getId() {
        return this.id;
    }

    public void setId(SampleRunId id) {
        this.id = id;
    }

    public int getRunId() {
        return this.id.getRunId();
    }

    public void setRunId(int runId) {
        this.id.setRunId(runId);
    }

    public int getsamId() {
        return this.id.getSamId();
    }

    public void setsamId(int samId) {
        this.id.setSamId(samId);
    }

    public Sample getsample() {
        return this.sample;
    }

    public void setsample(Sample sample) {
        this.sample = sample;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Reagent getReagentBySequencingReagentCode() {
        return this.reagentBySequencingReagentCode;
    }

    public void setReagentBySequencingReagentCode(
            Reagent reagentBySequencingReagentCode) {
        this.reagentBySequencingReagentCode = reagentBySequencingReagentCode;
    }

    public Reagent getReagentByClustergenerationReagentCode() {
        return this.reagentByClustergenerationReagentCode;
    }

    public void setReagentByClustergenerationReagentCode(
            Reagent reagentByClustergenerationReagentCode) {
        this.reagentByClustergenerationReagentCode = reagentByClustergenerationReagentCode;
    }

    public Reagent getReagentBySamplePrepReagentCode() {
        return this.reagentBySamplePrepReagentCode;
    }

    public void setReagentBySamplePrepReagentCode(
            Reagent reagentBySampleprepReagentCode) {
        this.reagentBySamplePrepReagentCode = reagentBySampleprepReagentCode;
    }

    public String getFlowcell() {
        return this.flowcell;
    }

    public void setFlowcell(String flowcell) {
        this.flowcell = flowcell;
    }

    /*public int getLane() {
     return this.lane;
     }

     public void setLane(int lane) {
     this.lane = lane;
     }*/
    public String getRunFolder() {
        return this.runFolder;
    }

    public void setRunFolder(String runfolder) {
        this.runFolder = runfolder;
    }

    public boolean getIsControl() {
        return this.isControl;
    }

    public void setControl(boolean iscontrol) {
        this.isControl = iscontrol;
    }

    public Set<RawData> getRawDatas() {
        return this.rawDatas;
    }

    public void setRawDatas(Set<RawData> rawdatas) {
        this.rawDatas = rawdatas;
    }

    /**
     * @return the lanes
     */
    public Set<Lane> getLanes() {
        return lanes;
    }

    /**
     * @param lanes the lanes to set
     */
    public void setLanes(Set<Lane> lanes) {
        this.lanes = lanes;
    }

}

src/main/java/it/iit/genomics/cru/smith/runsBeans/RunDetailsBean.java
package it.iit.genomics.cru.smith.runsBeans;

import it.iit.genomics.cru.smith.defaults.NgsLimsUtility;
import it.iit.genomics.cru.smith.defaults.Preferences;
import it.iit.genomics.cru.smith.entity.MultipleRequest;
import it.iit.genomics.cru.smith.entity.Sample;
import it.iit.genomics.cru.smith.entity.SampleRun;
import it.iit.genomics.cru.smith.entity.User;
import it.iit.genomics.cru.smith.hibernate.HibernateUtil;
import it.iit.genomics.cru.smith.userBeans.LoggedUser;
import it.iit.genomics.cru.smith.userBeans.LoggedUserBean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * @(#)RunDetailsBean.java 20 JUN 2014 Copyright 2014 Computational Research
 * Unit of IIT@SEMM. All rights reserved. Use is subject to MIT license terms.
 *
 * Backing bean for sample run details.
 *
 * @author Francesco Venco
 * @version 1.0
 * @since 1.0
 */
@ManagedBean(name = "runDetailsBean")
//@SessionScoped
@ViewScoped
public class RunDetailsBean implements Serializable {

    //protected List<SampleRunFormBean> sampleruns;
    private List<SampleRun> sampleruns;
    private ArrayList<Integer> sampleToBeAdded;
    private int runID;
    private String formId;
    private boolean runIsClosed;
    private boolean allConfirmed;

    /**
     * Bean constructor
     *
     * @author Francesco Venco
     * @since 1.0
     */
    public RunDetailsBean() {
        if(Preferences.getVerbose()){
            System.out.println("init RunDetailsBean");
        }
        
        formId = "rundetailsForm";
        FacesContext context = FacesContext.getCurrentInstance();
        String rid = (String) context.getExternalContext().getRequestParameterMap().get("rid");
        if (rid != null) {
            runID = Integer.parseInt(rid);
        } else {
            runID = -1;
        }
        sampleruns = RunHelper.getRunsList(runID);
        //check for samples requested toghether but not yet
        //put in the run
        sampleToBeAdded = new ArrayList<Integer>();
        HashSet<Integer> sampleToBeAddedSet = new HashSet<Integer>();
        HashSet<Integer> sampleRequestIds = new HashSet<Integer>();
        //find all ids or requests. Check if the run
        //is still open for modifications ( i.e. not all samples
        //have been confirmed yet)
        runIsClosed = true;
        allConfirmed = true;
        for (SampleRun sr : sampleruns) {
            String status = sr.getsample().getStatus();
            if (status.equals(Sample.status_queued) || status.equals(Sample.status_confirmed)) {
                runIsClosed = false;
            }
            if (!sr.getsample().getStatus().equals(Sample.status_confirmed)) {
                allConfirmed = false;
            }
            Set<MultipleRequest> mrs = sr.getsample().getMultipleRequests();
            if (!mrs.isEmpty()) {
                for (MultipleRequest mr : mrs) {
                    sampleRequestIds.add(mr.getId().getRequestId());
                }
            }
        }
        //add ids of samples requested along with the ones in the run
        for (Integer i : sampleRequestIds) {
            List<MultipleRequest> possiblyMissing = RunHelper.getRequestList(i);
            for (MultipleRequest mr : possiblyMissing) {
                sampleToBeAddedSet.add(mr.getId().getSampleId());
            }
        }
        //remove the ones already inserted
        for (SampleRun sr : sampleruns) {
            sampleToBeAddedSet.remove(sr.getsample().getId());
        }
        System.out.println(sampleToBeAddedSet);
        for (Integer i : sampleToBeAddedSet) {
            sampleToBeAdded.add(i);
            System.out.println("Adding to list :" + i);
        }
        System.out.println(sampleToBeAdded);
        NgsLimsUtility.setFailMessage(formId, "missing", "Missing Samples in the Run ", "Other samples have been requested along with the selected ones:");

    }

    /**
     * Getter for sampleruns
     *
     * @author Francesco Venco
     * @return List<SampleRun>
     * @since 1.0
     */
    public List<SampleRun> getSampleruns() {
        return this.sampleruns;
    }

    /**
     * Getter for runID
     *
     * @author Francesco Venco
     * @return int
     * @since 1.0
     */
    public int getRunID() {
        return this.runID;
    }

    /**
     * Close run action listener.
     *
     * @author Francesco Venco
     * @return String - a redirect to the run details page
     * @since 1.0
     */
    public String closeRun() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        List<SampleRun> runsList = null;
        Transaction tx = null;
        try {
            tx = session.beginTransaction();
            Query q = session.createQuery("from SampleRun as s where s.id.runId = '" + runID + "'");
            runsList = (List<SampleRun>) q.list();
            //for for lazy initialization
            for (int i = 0; i < runsList.size(); i++) {
                SampleRun csr = runsList.get(i);
                csr.getsample().setStatus("running");
                session.saveOrUpdate(csr.getsample());
            }
            tx.commit();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
        session.close();
        return "runDetails.jsf?rid=" + runID + " faces-redirect=true";
    }

    /**
     * Tests if logged user has permission to add a sample run.
     *
     * @author Francesco Venco
     * @return boolean
     * @since 1.0
     */
    public boolean getUserHasAddPermission() {
        FacesContext context = FacesContext.getCurrentInstance();       
        LoggedUser lu = ((LoggedUser) context.getApplication().evaluateExpressionGet(context, "#{loggedUserBean}", LoggedUserBean.class)); 
        //User loggeduser = new LoggedUser().getLoggedUser();
        User loggeduser = lu.getLoggedUser();
        return (loggeduser.getUserRole().equals(Preferences.ROLE_TECHNICIAN) || loggeduser.getUserRole().equals(Preferences.ROLE_ADMIN));
    }

    /**
     * Getter for sampleToBeAdded.
     *
     * @author Francesco Venco
     * @return ArrayList<Integer>
     * @since 1.0
     */
    public ArrayList<Integer> getSampleToBeAdded() {
        System.out.println("List: " + sampleToBeAdded);
        return sampleToBeAdded;
    }

    /**
     * Setter for sampleToBeAdded.
     *
     * @author Francesco Venco
     * @param sampleToBeAdded
     * @since 1.0
     */
    public void setSampleToBeAdded(ArrayList<Integer> sampleToBeAdded) {
        this.sampleToBeAdded = sampleToBeAdded;
    }

    /**
     * Tests if run is closed.
     *
     * @author Francesco Venco
     * @return boolean
     * @since 1.0
     */
    public boolean isRunIsClosed() {
        return runIsClosed;
    }

    /**
     * Setter for runIsClosed.
     *
     * @author Francesco Venco
     * @param runIsClosed
     * @since 1.0
     */
    public void setRunIsClosed(boolean runIsClosed) {
        this.runIsClosed = runIsClosed;
    }

    /**
     * Tests if all samples are confirmed to be run.
     *
     * @author Francesco Venco
     * @return boolean
     * @since 1.0
     */
    public boolean isAllConfirmed() {
        return allConfirmed;
    }
}

src/main/webapp/Run/runDetails.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"    
                xmlns:p="http://primefaces.org/ui"
                template="/template.xhtml">

    <ui:define name="runDetails" >      
   
        
        
        <h:form id="rundetailsForm"  >
            
             
            <h3>Run #{runDetailsBean.runID} details</h3>
            
                <p:scrollPanel  id="sampleruns"  style="width:500px;height:500px">
                    <p:dataGrid  value="#{runDetailsBean.sampleruns}" var="sampleRun" id="samplerunsgrid" columns="1">
                        <p:button icon="ui-icon-search" outcome="samplerunDetails.jsf"  title="#{bundle['runs.view.detail']}" >
                            <f:param value="#{sampleRun.id.samId}" name="sid" />
                            <f:param name="rid" value="#{runDetailsBean.runID}" /> 
                        </p:button>
                        <h:outputText value="#{bundle['runs.sample']}#{sampleRun.samId}#{bundle['runs.operator']} #{sampleRun.user.login}" style="margin-left:10px" />
                    </p:dataGrid>
                </p:scrollPanel>
            
            
             
            
          
            
            <p:button  outcome="selectSample.jsf"  value="#{bundle['button.text.add.sample']}" rendered="#{runDetailsBean.userHasAddPermission}" 
                              disabled="#{runDetailsBean.runIsClosed}" >
                <f:param name="specifySamples" value="requested"/>
                <f:param name="rid" value="#{runDetailsBean.runID}" />
            </p:button>
            
            <p:commandButton action="#{runDetailsBean.closeRun}"  value="#{bundle['button.text.close.run']}" rendered="#{runDetailsBean.userHasAddPermission}" 
                              disabled="#{!runDetailsBean.allConfirmed}" >
            </p:commandButton>
            
            
            <h></h>
             
            <p:message for="missing"  rendered="#{!runDetailsBean.sampleToBeAdded.isEmpty()}"  />
            <h></h>
            <p:scrollPanel  id="missing"  style="width:500px;height:500px" rendered="#{!runDetailsBean.sampleToBeAdded.isEmpty()}">
                    <p:dataGrid  value="#{runDetailsBean.sampleToBeAdded}" var="missingSample" id="missinggrid" columns="1">
                        <p:button icon="ui-icon-pencil" outcome="newSampleRunForm.jsf"  title="#{bundle['button.text.add.sample']}" >
                            <f:param value="#{missingSample}" name="sid" />
                            <f:param name="rid" value="#{runDetailsBean.runID}" /> 
                        </p:button>
                        <h:outputText value="sample (#{missingSample})"  style="margin-left:10px" />
                    </p:dataGrid>
           </p:scrollPanel>
            
            
            
            
         </h:form>
               
    </ui:define>

</ui:composition>

src/main/webapp/Run/runsSearch.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"    
                xmlns:p="http://primefaces.org/ui"
                template="/template.xhtml">

    <ui:define name="runsSearch">


        <h:form id="runsTableForm">
    
        
        <p:dataTable id="runsTable" var="runs" value="#{runsSearchBean.runsList}" widgetVar="samplesTable"
                     style="font-size: x-small;" paginator="true" rows="20"
                     paginatorTemplate="{FirstPageLink} {PreviousPageLink} {RowsPerPageDropdown}
                                        {CurrentPageReport} {NextPageLink} {LastPageLink}"
                     emptyMessage="#{bundle['runs.emptymessage']}" filteredValue="#{filterBean.sampleRun}"  >
          

            <p:column id="idRunsColumn" filterBy="#{runs.id.runId}"                     
                      headerText="#{bundle['runs.run.id']}"
                      filterMatchMode="contains">
                <h:link  outcome="runDetails.jsf">
                        <f:param name="rid" value="#{runs.id.runId}"/>
                        <h:outputText value="#{runs.id.runId}"/>                         
                 </h:link> 
            </p:column>
             
            <p:column id="idSamColumn" filterBy="#{runs.id.samId}"                      
                      headerText="#{bundle['runs.sample.id']}"
                      filterMatchMode="contains">
                 <h:commandLink target="_blank" action="#{modSampleFormBean.loadid(runs.id.samId)}" >
                        <h:outputText value="#{runs.id.samId}"/>   
                 </h:commandLink>   
            </p:column>
            
            <p:column id="operatorColumn" filterBy="#{runs.user.login}"                      
                      headerText="#{bundle['runs.operator.header']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.user.login}" />
            </p:column>
            
            <p:column id="requesterColumn" filterBy="#{runs.sample.user.login}"                      
                      headerText="#{bundle['runs.requester']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.sample.user.login}" />
            </p:column>
                     
            <p:column id="seqColumn" filterBy="#{runs.reagentBySequencingReagentCode.reagentBarCode}"                      
                      headerText="#{bundle['runs.sequencing.reagent']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.reagentBySequencingReagentCode.reagentBarCode}" />
            </p:column>
            
            <p:column id="clusterGenColumn" filterBy="#{runs.reagentByClustergenerationReagentCode.reagentBarCode}"                      
                      headerText="#{bundle['runs.cluster.reagent']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.reagentByClustergenerationReagentCode.reagentBarCode}" />
            </p:column>
            
            <p:column id="prepColumn" filterBy="#{runs.reagentBySamplePrepReagentCode.reagentBarCode}"                      
                      headerText="#{bundle['runs.sampleprep.ragent']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.reagentBySamplePrepReagentCode.reagentBarCode}" />
            </p:column>
            
            <p:column id="flowcellColumn" filterBy="#{runs.flowcell}"                      
                      headerText="#{bundle['runs.flowcell']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.flowcell}" />
            </p:column>
            
            <p:column id="laneColumn" filterBy="#{runs.allLanesToString}"                      
                      headerText="#{bundle['runs.lane']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.allLanesToString}" />
            </p:column>
            
            <p:column id="seqindexColumn" filterBy="#{runs.sample.sequencingIndexes.index}"                      
                      headerText="#{bundle['runs.sequencing.index']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.sample.sequencingIndexes.index}" />
            </p:column>
            
            <p:column id="isControlColumn" filterBy="#{runs.isControl}"                      
                      headerText="#{bundle['runs.is.control']}"
                      filterMatchMode="contains">
                 <h:outputText value="#{runs.isControl}" />
            </p:column>
            
            <p:column id="runFolderColumn" filterBy="#{runs.runFolder}"                      
                      headerText="#{bundle['runs.run.folder']}"
                      filterMatchMode="contains">                 
                <h:outputLink target="_blank" value="#{runsSearchBean.fastqhyperlink}#{runs.runFolder}" >
                        <h:outputText value="#{runs.runFolder}" />
                 </h:outputLink>   
            </p:column>
                        
            
        </p:dataTable>
        <h:panelGrid columns="2">
                <p:panel header="#{bundle['export.All']}">
                    <h:commandLink>
                        <p:graphicImage value="/img/csv.png" />
                        <p:dataExporter type="csv" target="runsTable" fileName="Runs" pageOnly="false" />
                    </h:commandLink>

                </p:panel>
            <p:panel header="#{bundle['export.Page']}">
                    <h:commandLink>
                        <p:graphicImage value="/img/csv.png" />
                        <p:dataExporter type="csv" target="runsTable" fileName="Runs" pageOnly="true" />
                    </h:commandLink>

                </p:panel>

            </h:panelGrid>    
     
           <h3> #{bundle['runs.hint']} </h3>
          
           
           
           
           <p:button outcome="selectSample.jsf"  value="#{bundle['button.text.new.run']}" disabled="#{!runsSearchBean.userHasAddPermission}">
                <f:param name="specifySamples" value="requested"/>
                <f:param name="rid" value="#{runsSearchBean.newRunId}" />
            </p:button>
           
           
           
           <p:button outcome="newDraggableRunForm.jsf"  value="Mindex" disabled="#{!runsSearchBean.userHasAddPermission}" rendered="true">
                <f:param name="specifySamples" value="requested"/>
                <f:param name="rid" value="#{runsSearchBean.newRunId}" />
            </p:button>
           
            </h:form>
           
           
           <p:separator/>
            
        <h2>Upload Run Form</h2>
        <h:outputLink rendered="#{navigationBean.userHasAddPermission}" id="runUploadFormDownload" value="../downloads/examplerunform.csv">
                <h:outputText value="#{bundle['runs.exampleform']}" />
            </h:outputLink>
        
        <h:form id="runTableUploadForm" >
            
            <p:panelGrid columns="3">
                <p:fileUpload immediate="true"  id="fu3"  style="margin-top: 10px" fileUploadListener="#{uploadRunFormBean.handleFileUpload}"  
                              sizeLimit="100000000" allowTypes="/(\.|\/)(csv|txt)$/" mode="advanced"  update="ufilename">
                </p:fileUpload>

                <h:outputText id="ufilename"  value="#{uploadRunFormBean.filename}" ></h:outputText>
                


            </p:panelGrid>
        </h:form>
        
        <h:form  id="runTableUploadProcessForm">
            
            <p:commandButton id="RunUploadProcessButton" action="#{uploadRunFormBean.submitSampleRun()}" value="#{bundle['button.text.new.sample.upload']}" update="@all" >
                </p:commandButton>
        </h:form>
           
           
        
    </ui:define>

</ui:composition>